name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: ci
    uses: betabitplus/ternforge-infra-ci/.github/workflows/python-library.yml@df435ecb7f5f3e538a3d90a1002525a6354662ed # v1.5.0
    with:
      python-version: "3.13"
      policy-command: py-lib-policy check
      runtime-audit-exclude-package: py-lib-runtime
