name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: betabitplus/ternforge-infra-ci/.github/workflows/release.yml@df435ecb7f5f3e538a3d90a1002525a6354662ed # v1.5.0
    with:
      app-client-id: ${{ vars.TERNFORGE_RELEASE_CLIENT_ID }}
      repository: ${{ github.event.repository.name }}
      release-type: python
      synchronize-python-lock: true
    secrets:
      app-private-key: ${{ secrets.TERNFORGE_RELEASE_PRIVATE_KEY }}
